# Usage:
#   docker-compose up -d             # runs with Neon (remote DB)
#   docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d   # runs with local DB

services:
  api:
    build: .
    ports:
      - "8081:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=ep-curly-bread-aqpm5xf6.c-8.us-east-1.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_aRz2IuKo9xPA;SSL Mode=Require"
